'use strict';
const MIN_DATE='2026-09-14',MIN_MONTH=new Date(2026,8,1),WEEK=['일','월','화','수','목','금','토'];
const $=s=>document.querySelector(s);let db,currentMonth,records=new Map(),activeDate='',activeRecord=null,viewerPhotoId=null,memoTimer;
const els={calendar:$('#calendar'),monthTitle:$('#monthTitle'),prev:$('#prevBtn'),next:$('#nextBtn'),backdrop:$('#backdrop'),daySheet:$('#daySheet'),dayTitle:$('#dayTitle'),poop:$('#poopToggle'),run:$('#runToggle'),photos:$('#photoGrid'),photoInput:$('#photoInput'),memo:$('#memo'),message:$('#message'),streak:$('#streakSummary span')};
function keyOf(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const runDetails=$('#runDetails'),runLaps=$('#runLaps'),runMinutes=$('#runMinutes'),foodText=$('#foodText');let detailSaveTimer;
function optionalInteger(input){return input.value===''?undefined:Math.max(0,Math.floor(Number(input.value)||0))}
function setRunDetailsVisibility(){runDetails.hidden=els.run.getAttribute('aria-pressed')!=='true'}
function queueDetailSave(){clearTimeout(detailSaveTimer);detailSaveTimer=setTimeout(()=>db&&activeDate&&saveRecord(),350)}
function fillOptionalFields(){if(!activeRecord)return;runLaps.value=activeRecord.runLaps??'';runMinutes.value=activeRecord.runMinutes??'';foodText.value=activeRecord.foodText||'';setRunDetailsVisibility()}
function initExtraEvents(){
  els.calendar.addEventListener('click',e=>{if(e.target.closest('[data-date]'))setTimeout(fillOptionalFields)});
  els.run.addEventListener('click',()=>setTimeout(setRunDetailsVisibility));
  [runLaps,runMinutes].forEach(input=>input.addEventListener('input',()=>{if(!activeRecord)return;activeRecord.run=true;els.run.setAttribute('aria-pressed','true');setRunDetailsVisibility();activeRecord.runLaps=optionalInteger(runLaps);activeRecord.runMinutes=optionalInteger(runMinutes);records.set(activeDate,activeRecord);queueDetailSave()}));
  foodText.addEventListener('input',()=>{if(!activeRecord)return;activeRecord.foodText=foodText.value.trim();records.set(activeDate,activeRecord);queueDetailSave()});
}
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open('poop-calendar',1);req.onupgradeneeded=()=>req.result.createObjectStore('days',{keyPath:'date'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function tx(mode='readonly'){return db.transaction('days',mode).objectStore('days')}
function loadAll(){return new Promise((resolve,reject)=>{const req=tx().getAll();req.onsuccess=()=>{records=new Map(req.result.map(r=>[r.date,r]));resolve()};req.onerror=()=>reject(req.error)})}
function saveRecord(){activeRecord.memo=els.memo.value.trim();records.set(activeDate,activeRecord);return new Promise((resolve,reject)=>{const req=tx('readwrite').put(activeRecord);req.onsuccess=resolve;req.onerror=()=>reject(req.error)}).then(render).catch(storageError)}
function storageError(){els.message.textContent='기록을 저장하지 못했어요. Safari 저장 공간을 확인해 주세요.'}
function mini(type){return `<svg class="mini-sticker ${type==='run'?'mini-run':''}" viewBox="0 0 ${type==='run'?'110 76':'86 76'}" aria-hidden="true"><use href="#${type==='run'?'shoe':'poop'}-shape"/></svg>`}
function render(){const y=currentMonth.getFullYear(),m=currentMonth.getMonth(),first=new Date(y,m,1).getDay(),last=new Date(y,m+1,0).getDate(),today=keyOf(new Date());els.monthTitle.textContent=`${y}년 ${m+1}월`;els.prev.disabled=y===2026&&m===8;let html='';for(let i=0;i<first;i++)html+='<span class="day empty"></span>';for(let d=1;d<=last;d++){const date=new Date(y,m,d),key=keyOf(date),r=records.get(key),disabled=key<MIN_DATE,marks=(r?.poop?mini('poop'):'')+(r?.run?mini('run'):'')+(r?.photos?.length?(r.photos[0].dataURL?`<img class="thumb" src="${r.photos[0].dataURL}" alt="">`:'<i class="photo-mark"></i>'):'');html+=`<button class="day${disabled?' disabled':''}${key===today?' today':''}${key===activeDate?' selected':''}" data-date="${key}" ${disabled?'disabled':''} role="gridcell" aria-label="${m+1}월 ${d}일${r?.poop?', 응가 기록':''}${r?.run?', 러닝 기록':''}${r?.photos?.length?', 음식 사진 있음':''}"><span class="day-num">${d}</span><span class="marks">${marks}</span></button>`}els.calendar.innerHTML=html;renderRunStreak()}
function renderRunStreak(){let cursor=new Date(),count=0;cursor.setHours(12,0,0,0);if(!records.get(keyOf(cursor))?.run)cursor.setDate(cursor.getDate()-1);while(records.get(keyOf(cursor))?.run){count++;cursor.setDate(cursor.getDate()-1)}els.streak.textContent=count?`연속 러닝 ${count}일째`:'오늘 러닝해볼까요'}
function changeMonth(delta){const next=new Date(currentMonth.getFullYear(),currentMonth.getMonth()+delta,1);if(next<MIN_MONTH)return;currentMonth=next;render()}
function showSheet(sheet){els.backdrop.hidden=false;sheet.hidden=false;requestAnimationFrame(()=>sheet.classList.add('open'))}
function closeSheets(){if(activeDate&&activeRecord){clearTimeout(memoTimer);activeRecord.memo=els.memo.value.trim();records.set(activeDate,activeRecord);if(db)try{const req=tx('readwrite').put(activeRecord);req.onerror=storageError}catch(e){storageError()}}document.querySelectorAll('.sheet.open').forEach(s=>s.classList.remove('open'));els.backdrop.hidden=true;setTimeout(()=>document.querySelectorAll('.sheet:not(.open)').forEach(s=>s.hidden=true),300);activeDate='';render()}
function openDay(key){activeDate=key;activeRecord=records.get(key)||{date:key,poop:false,run:false,photos:[],memo:''};activeRecord.photos=activeRecord.photos||[];const [y,m,d]=key.split('-').map(Number),date=new Date(y,m-1,d);els.dayTitle.textContent=`${m}월 ${d}일 (${WEEK[date.getDay()]})`;els.poop.setAttribute('aria-pressed',Boolean(activeRecord.poop));els.run.setAttribute('aria-pressed',Boolean(activeRecord.run));els.memo.value=activeRecord.memo||'';renderPhotos();showSheet(els.daySheet);render()}
function renderPhotos(){els.photos.innerHTML=(activeRecord.photos||[]).map(p=>`<button class="photo-item" data-photo="${p.id}" aria-label="음식 사진 크게 보기"><img src="${p.dataURL}" alt="먹은 음식 사진"></button>`).join('')+'<button class="add-photo" type="button" id="addPhoto" aria-label="사진 추가"><b>＋</b>사진 추가</button>';$('#addPhoto').onclick=()=>els.photoInput.click()}
function resizePhoto(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{let w=img.width,h=img.height,scale=Math.min(1,1280/Math.max(w,h));w=Math.round(w*scale);h=Math.round(h*scale);const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(img,0,0,w,h);resolve(canvas.toDataURL('image/jpeg',.8))};img.src=reader.result};reader.readAsDataURL(file)})}
async function addPhotos(files){try{for(const file of files){if(!file.type.startsWith('image/'))continue;const dataURL=await resizePhoto(file);activeRecord.photos.push({id:crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,dataURL,createdAt:new Date().toISOString()})}renderPhotos();await saveRecord()}catch(e){storageError()}els.photoInput.value=''}
function toggle(el,field){activeRecord[field]=!activeRecord[field];el.setAttribute('aria-pressed',activeRecord[field]);records.set(activeDate,activeRecord);render();if(activeRecord[field]){el.classList.remove('pop');void el.offsetWidth;el.classList.add('pop')}if(db)saveRecord();else storageError()}
function initEvents(){els.calendar.onclick=e=>{const day=e.target.closest('[data-date]');if(day)openDay(day.dataset.date)};els.prev.onclick=()=>changeMonth(-1);els.next.onclick=()=>changeMonth(1);let sx=0;els.calendar.addEventListener('touchstart',e=>sx=e.changedTouches[0].clientX,{passive:true});els.calendar.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>55)changeMonth(dx<0?1:-1)},{passive:true});els.poop.onclick=()=>toggle(els.poop,'poop');els.run.onclick=()=>toggle(els.run,'run');els.photoInput.onchange=()=>addPhotos([...els.photoInput.files]);els.memo.oninput=()=>{clearTimeout(memoTimer);memoTimer=setTimeout(()=>db&&saveRecord(),350)};els.photos.onclick=e=>{const item=e.target.closest('[data-photo]');if(!item)return;viewerPhotoId=item.dataset.photo;const p=activeRecord.photos.find(x=>x.id===viewerPhotoId);$('#viewerImg').src=p.dataURL;$('#viewer').hidden=false};$('#viewerClose').onclick=()=>$('#viewer').hidden=true;$('#deletePhotoBtn').onclick=()=>{if(confirm('이 사진을 지울까요?')){activeRecord.photos=activeRecord.photos.filter(p=>p.id!==viewerPhotoId);$('#viewer').hidden=true;renderPhotos();saveRecord()}};els.backdrop.onclick=closeSheets;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeSheets)}
async function init(){const now=new Date();currentMonth=now<MIN_MONTH?new Date(MIN_MONTH):new Date(now.getFullYear(),now.getMonth(),1);initEvents();render();try{db=await openDB();await loadAll();navigator.storage?.persist?.().catch(()=>{});render()}catch(e){storageError();render()}if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{els.message.textContent='오프라인 준비를 완료하지 못했어요. HTTPS 주소인지 확인해 주세요.'})}
initExtraEvents();
init();

// Best-effort daily backup to the home server (cross-origin: this app now lives on GitHub Pages).
// Silently skipped when the PC is off, retried next time the app opens.
const BACKUP_URL='https://appointee-unnoticed-donated.ngrok-free.dev/api/app-backup/poop-calendar';
async function dailyBackup(){try{const today=new Date().toISOString().slice(0,10);if(localStorage.getItem('poop-backup-date')===today)return;if(!db)await openDB().then(async d=>{db=d;await loadAll()});const res=await fetch(BACKUP_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Array.from(records.values()))});if(res.ok)localStorage.setItem('poop-backup-date',today)}catch(e){}}
setTimeout(dailyBackup,3000);
